# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170113_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',)},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ('line_text',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag_name',)},
        ),
        migrations.RemoveField(
            model_name='line',
            name='category',
        ),
        migrations.RemoveField(
            model_name='line',
            name='tag',
        ),
        migrations.AddField(
            model_name='line',
            name='categories',
            field=models.ManyToManyField(to='app.Category'),
        ),
        migrations.AddField(
            model_name='line',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
